framework:
    mailer:
        transports:
            # 1. Transport pour le système (Notifications)
            system: '%env(SYSTEM_MAILER_DSN)%'
            
            # 2. Transport pour le support (Formulaires clients)
            support: '%env(SUPPORT_MAILER_DSN)%'
        dkim_signer:
            key: 'file://%kernel.project_dir%/var/certificates/dkim.pem'
            domain: 'protic.com'
            select: 's1'
        smime_signer:
            key: '%kernel.project_dir%/var/certificates/smime.key'
            certificate: '%kernel.project_dir%/var/certificates/smime.crt'
            passphrase: ''
