sonata_admin:
    show_mosaic_button: false
    options:
        use_icheck: false
        use_select2: true
    title: 'Sonata Admin'
    title_logo: 'images/logo.png'
    persist_filters: true
    
    assets:
        remove_stylesheets:
            ["bundles/sonataadmin/app.css"]
        remove_javascripts:
            ["bundles/sonataadmin/app.js"]
    templates:
        layout: 'bundles/SonataAdminBundle/standard_layout.html.twig'

    default_admin_services:
        route_generator: App\Route\SonataRouteGenerator
    default_controller: App\Controller\Admin\WlindablaAdminCRUDController
    
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            app.admin.group.user:
                label: Administration
                keep_open: true
            app.admin.group.catalogue:
                keep_open: true
                label: Catalogue
                icon: bi bi-journals
            app.admin.group.load:
                keep_open: true
                label: Demandes
                icon: bi bi-envelope-fill
            app.admin.group.configuration:
                 keep_open: true
                 icon: bi bi-cogs
                 label: Configuration
            app.admin.group.faq:
                label: Gestion du Contenu
                keep_open: true
sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
