sonata_admin:
    show_mosaic_button: false
    security:
        handler: sonata.admin.security.handler.role

    options:
        use_icheck: false
        use_select2: true
    title: 'ProTIC Editions & Services'
    title_logo: 'images/logo.png'
    persist_filters: true
    
    assets:
        remove_stylesheets:
            ["bundles/sonataadmin/app.css"]
        remove_javascripts:
            ["bundles/sonataadmin/app.js"]
    templates:
        layout: 'bundles/SonataAdminBundle/standard_layout.html.twig'

    default_admin_services:
        route_generator: App\Route\SonataRouteGenerator
        #security_handler: App\Security\Handler\AbstractRoleSecurityHandler
    default_controller: App\Controller\Admin\WlindablaAdminCRUDController
    
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            app.admin.group.user:
                label: Administration
                icon: bi bi-people
                keep_open: true
            app.admin.group.catalogue:
                keep_open: true
                label: Catalogue
                icon:  bi bi-book
            app.admin.group.load:
                keep_open: true
                label: Demandes
                icon: bi bi-envelope-fill
            app.admin.group.configuration:
                 keep_open: true
                 icon: bi bi-gear-wide-connected
                 label: Configuration
            app.admin.group.faq:
                label: Gestion du Contenu
                keep_open: true
                icon: bi bi-menu-button-wide-fill
            app.admin.group.permission.manager:
                label: Gestion des Permissions
                icon: bi bi-backpack2

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
