<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260515202038 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_sessions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_identifier VARCHAR(255) NOT NULL, session_id VARCHAR(255) NOT NULL, ip_address VARCHAR(255) DEFAULT NULL, user_agent VARCHAR(500) DEFAULT NULL, device_fingerprint VARCHAR(100) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_activity_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, active BOOLEAN NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7AED7913613FECDF ON user_sessions (session_id)');
        $this->addSql('CREATE INDEX idx_user_session_identifier ON user_sessions (user_identifier)');
        $this->addSql('CREATE INDEX idx_user_session_id ON user_sessions (session_id)');
        $this->addSql('CREATE INDEX idx_user_session_last_activity ON user_sessions (last_activity_at)');
        $this->addSql('CREATE INDEX idx_user_session_active ON user_sessions (active)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE user_sessions');
    }
}
