<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260415221348 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE permission_role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description TEXT NOT NULL, context VARCHAR(200) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6A711CA5E237E06 ON permission_role (name)');
        $this->addSql('CREATE INDEX IDX_6A711CAB03A8386 ON permission_role (created_by_id)');
        $this->addSql('CREATE TABLE user_permission_role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, assigned_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, scope VARCHAR(100) DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, permission_role_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_147B7D45E112C3FB ON user_permission_role (permission_role_id)');
        $this->addSql('ALTER TABLE permission_role ADD CONSTRAINT FK_6A711CAB03A8386 FOREIGN KEY (created_by_id) REFERENCES sonata_user (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_permission_role ADD CONSTRAINT FK_147B7D45E112C3FB FOREIGN KEY (permission_role_id) REFERENCES permission_role (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sonata_user ADD is_member BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE sonata_user ADD team_position SMALLINT DEFAULT NULL');
        $this->addSql('ALTER TABLE sonata_user ADD team_bio TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE sonata_user ADD team_initial VARCHAR(5) DEFAULT NULL');
        $this->addSql('ALTER TABLE sonata_user ADD team_alt_text VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE permission_role DROP CONSTRAINT FK_6A711CAB03A8386');
        $this->addSql('ALTER TABLE user_permission_role DROP CONSTRAINT FK_147B7D45E112C3FB');
        $this->addSql('DROP TABLE permission_role');
        $this->addSql('DROP TABLE user_permission_role');
        $this->addSql('ALTER TABLE sonata_user DROP is_member');
        $this->addSql('ALTER TABLE sonata_user DROP team_position');
        $this->addSql('ALTER TABLE sonata_user DROP team_bio');
        $this->addSql('ALTER TABLE sonata_user DROP team_initial');
        $this->addSql('ALTER TABLE sonata_user DROP team_alt_text');
    }
}
