parameters:
     router.request_context.scheme: 'https'
     asset.request_context.secure: true
     NAME_SITE: "ProTIC Editions & Services"
     app.site_name: "ProTIC Editions & Services"
     dkim_key: '%env(resolve:default::MAILER_DKIM)%'
     app.mail.from:
        system:
            address: '%env(APP_MAIL_FROM_SYSTEM)%'
            name: '%env(APP_MAIL_FROM_SYSTEM_NAME)%'
        support:
            address: '%env(APP_MAIL_FROM_SUPPORT)%'
            name: '%env(APP_MAIL_FROM_SUPPORT_NAME)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    App\:
        resource: '../src/'

    pentatrion_vite.asset_strategy_app:
        parent: Pentatrion\ViteBundle\Asset\ViteAssetVersionStrategy
        calls:
            - [setConfig, ['app']]

    pentatrion_vite.asset_strategy_admin:
        parent: Pentatrion\ViteBundle\Asset\ViteAssetVersionStrategy
        calls:
            - [setConfig, ['admin']]
            
    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'
            - { 'prefix': 'orind_sess:', 'ttl': 3600 }

    Redis:
        class: \Redis
        lazy: true
        calls:
            - connect:
                - '%env(REDIS_HOST)%'
                - '%env(int:REDIS_PORT)%'
            - setOption: [!php/const Redis::OPT_READ_TIMEOUT, -1]

    gedmo.mapping.driver.attribute:
        class: Gedmo\Mapping\Driver\AttributeReader
    
    gedmo.listener.softdeleteable:
        class: Gedmo\SoftDeleteable\SoftDeleteableListener
        tags:
        - { name: doctrine.event_listener, event: 'onFlush' }
        - { name: doctrine.event_listener, event: 'loadClassMetadata' }
        calls:
        - [ setAnnotationReader, [ "@gedmo.mapping.driver.attribute" ] ]
        
    libphonenumber\PhoneNumberUtil:
        factory: ['libphonenumber\PhoneNumberUtil', 'getInstance']
    
    # Mailer Factory
    App\Service\Mailing\MailerFactory:
        arguments:
            $fromAddresses: '%app.mail.from%'

when@dev:
    services:
        App\DataFixtures\BookFixtures:
            arguments:
                $projectDir: '%kernel.project_dir%'

        App\DataFixtures\ManuscriptSubmissionFixtures:
            arguments:
                $projectDir: '%kernel.project_dir%'

        App\DataFixtures\SonataUserFixtures:
            arguments:
                $projectDir: '%kernel.project_dir%'
    